### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#101]
Is there anything we need to remove in order to make this repo public? How should we update the readme?

Edit (more clear goals):

My main goal for making the repo public is to update the icon section of the design handbook so that it is up-to-date: https://wordpress.com/design-handbook/

Stipulations: 
- Ok to make public. 
- Ok to fork
- Nobody external can suggest icons / add icons / else
- Social logos are in a separate repo: https://github.com/Automattic/social-logos

**Comment by folletto** [comment]
![screen shot 2016-03-01 at 15 55 15](https://cloud.githubusercontent.com/assets/4389/13432549/05df5024-dfc6-11e5-9f05-4dd05947ef12.png)

We're open! :)
