### ISSUE TITLE
Custom letterforms for icons (no Open Sans)

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#144]
I think we should consider custom letterforms, for some of our icons. The ? icon especially could use some help.

Left is current, options follow

![screen shot 2016-02-17 at 3 48 58 pm](https://cloud.githubusercontent.com/assets/618551/13619676/1bc26338-e550-11e5-8c77-f9b455fa60f1.png)

**Comment by mattmiklic** [comment]
I like the second from left, though it feels like it needs at least a little bit of a stem descending from the aperture of the `?`. Definitely feels like a better match for the icon style than the Open Sans-based glyph.

**Comment by jasmussen** [comment]
I also dig the second one from the left. 

As a sidenote, as small as this sounds, it'd be good to think up some guidelines for what drives these custom letterforms, outside of just the general Gridicon guidelines. I noticed Google added a bunch of custom letterforms to their material set recently, and it's quickly clear there's a ruleset to their letterforms:

![screen shot 2016-03-09 at 11 50 11](https://cloud.githubusercontent.com/assets/1204802/13633096/601c6cc0-e5ed-11e5-88db-4b09afb564fb.png)

![screen shot 2016-03-09 at 11 50 15](https://cloud.githubusercontent.com/assets/1204802/13633099/63070530-e5ed-11e5-8c5a-a86f22cd6e3a.png)

![screen shot 2016-03-09 at 11 50 36](https://cloud.githubusercontent.com/assets/1204802/13633104/650559a4-e5ed-11e5-9971-f05cefa370aa.png)

![screen shot 2016-03-09 at 11 50 41](https://cloud.githubusercontent.com/assets/1204802/13633105/670ddc8a-e5ed-11e5-8a2a-e1cdca788188.png)

The material style here is a little bit machinist and brutalist for my tastes. But I like how it's clearly a font, while at the same time clearly using the icon design language.

**Comment by drw158** [comment]
Some more options

![screen shot 2016-03-21 at 3 01 30 pm](https://cloud.githubusercontent.com/assets/618551/13932425/fd66e7bc-ef75-11e5-83de-5f61aad5552c.png)

**Comment by jasmussen** [comment]
1 and 3 look amazing, and 3 is my favorite. Nice work!

**Comment by mattmiklic** [comment]
Agreed, I like both 1 and 3; slight aesthetic preference for 3, but if we want these to adhere to the "straight 45º angles" rule then I'd go with 1.

**Comment by drw158** [comment]
I will move forward with 3

Thanks!

I tried to go with something like this, but couldn't get it to work on the grid

![screen shot 2016-03-21 at 4 56 23 pm](https://cloud.githubusercontent.com/assets/618551/13935569/f96a4b3a-ef85-11e5-93d1-ef1ecbeb9a67.png)
