### ISSUE TITLE
Remove the 'backspace' Gridicon

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#146]
This icon has been in the repo since the beginning, but I don't think I've ever seen it used anywhere. The style of Gridicons has changed, and I think that it either needs to be removed, or tweaked to match the rest of the set.

![screen shot 2016-03-17 at 10 56 09 am](https://cloud.githubusercontent.com/assets/618551/13852148/e0f5ce6c-ec2e-11e5-85d1-58459e95c5cc.png)

**Comment by jasmussen** [comment]
Sounds fine with me.
