### ISSUE TITLE
Add icon: package

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/gridicons#151]
Looking for a box/package icon for shipping.

Something like 

<img width="88" alt="screen shot 2016-03-31 at 10 27 28 am" src="https://cloud.githubusercontent.com/assets/5835847/14178996/3bc4e538-f72b-11e5-87f5-b2194d95c2eb.png">
<img width="80" alt="screen shot 2016-03-31 at 10 27 32 am" src="https://cloud.githubusercontent.com/assets/5835847/14178995/3bc3a1f0-f72b-11e5-9fa4-705d4bfcf26c.png">
<img width="90" alt="screen shot 2016-03-31 at 10 27 39 am" src="https://cloud.githubusercontent.com/assets/5835847/14178994/3bc184ce-f72b-11e5-8678-8942caff50ae.png">

**Comment by drw158** [comment]
Since we want to keep everything 2d, this will be hard, but here are some icons I whipped up for "shipment"

![screen shot 2016-03-31 at 12 09 44 pm](https://cloud.githubusercontent.com/assets/618551/14184338/4d089bbe-f73a-11e5-8fba-3124af4c2245.png)

**Comment by kellychoffman** [comment]
Nice. The truck for 'shipping' is great. For 'package' I think the first or third one, but I'm not sure how the third one would look small. I think a single package would be ideal because one of the ways I want to use it is to denote the package type: a box versus an envelope.

**Comment by drw158** [comment]
Cool, I think the first one will work well.

**Comment by kellychoffman** [comment]
Agree! Thanks, Dave.
