### ISSUE TITLE
Bug: "react-pure-render/mixin" required without being in package.json

### ISSUE THREAD

**Issue by coderkevin** [Automattic/gridicons#176]
'react-pure-render' is being required [here](https://github.com/Automattic/gridicons/blob/master/react/gridicon/index.jsx#L14) and [here](https://github.com/Automattic/gridicons/blob/master/react/gridicon/inc/index-header.jsx#L14).

However, package.json does not include this dependency.

**Comment by folletto** [comment]
It's kinda... correct. Even if I understand might not be clear.

`package.json` for Gridicons is for the build process of the Gridicons package as a whole, while the generated React code in the package is meant to be included in other React project, which will handle packages as they prefer. 

Does that sound right? :)

**Comment by coderkevin** [comment]
I'm not sure. Usually a package contains all dependencies needed. I've not worked with a package that didn't declare all of its dependencies before.

**Comment by folletto** [comment]
That's correct, but here these are two different things: the one you edited is `package.json` for the script that minifies, builds the sprites and the React component, it's not the `package.json` for the React component itself.

The `/react/gridicon` [folder](https://github.com/Automattic/gridicons/tree/master/react/gridicon) doesn't have any `package.json` file.

**Comment by coderkevin** [comment]
So, I wonder which precedent we should choose to set here. The only other similar case I know of is  [i18n-calypso](https://github.com/Automattic/i18n-calypso), but I imagine there will be more like this coming.

In the case of i18n-calypso, it looks like it includes dependencies the React component would need in the top-level dependencies. I guess we just need to figure out how we want to deal with dependencies and unify that strategy across all of our repos like this one. What are your thoughts? Are there others who should be involved in this decision as well?

**Comment by folletto** [comment]
In my view this is very different. The Gridicons repository is primarily a builder (all the scripts are building scripts to create the assets), and among the things it builds, it builds a react component. 

Instead, `i18n-calypso` is only the component, which gets published on NPM directly.

So, we'd be comparing apple to oranges here.

We could probably generate the `/react/gridicon` folder to be a full fledged NPM component, so it could be then more easily ported and even published (does the NPM registry allow publishing from a subfolder instead of the root of the GitHub project?).

**Comment by coderkevin** [comment]
That's a fair point, I suppose. It's possible to create a package for a subdirectory, it just makes extra steps for someone who wants to use the repo directly. Looks like folks have been asking for this kind of feature in npm for a while: https://github.com/npm/npm/issues/2974

If we were to publish a package from the subdir, it would depend on the package from the parent directory, which means we'd have to publish the parent directory as well, which would contain the subdirectory as well. Seems like a strange setup to me.

The other option would be to move the React component to its own repo, where it can be a first-class citizen with a package.json of its own. We'd still want to publish this repo separately and depend on it as well.

The only other option we'd have is to leave it as is and add explicit notes in the README as to which modules the React code depends on, and which version. But that seems sketchy too.

**Comment by folletto** [comment]
> If we were to publish a package from the subdir, it would depend on the package from the parent directory, which means we'd have to publish the parent directory as well, which would contain the subdirectory as well. Seems like a strange setup to me.
...
> We'd still want to publish this repo separately and depend on it as well.

I'm not sure I understand: why would it depend on the parent? What's the dependency?

**Comment by coderkevin** [comment]
Oh, my bad. I thought it had some dependency to the icons in the parent directory. If it's 100% independent of the parent directory after it's been generated, that simplifies things.

So, if it were published to npm separately, it could live as a separate entity and be happy that way with its own package.json and dependencies.

The only complication then would be for those of us wanting to use icons that have not yet been published on npm. But maybe that's just the motivation we'd need to keep npm current and publish often.

**Comment by folletto** [comment]
Yep independent. I'm not 100% sure, but I think the only needed bit is `index.jsx`.

Cool then! Let's see if we are thinking the same: the next step here could be to have the current generator to create a full, clean react component in a subfolder, so that can be easily copied 1:1 to a separate repository to be NPM published?

**Comment by coderkevin** [comment]
I'm not sure it needs to be in a separate repo. I think you could publish from the subdirectory it's already in.

**Comment by folletto** [comment]
Ok!

**Comment by drw158** [comment]
is this obsolete now that we have an npm package for the react component? #188
