### ISSUE TITLE
Money icon tweak

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#178]
It might make more sense in terms of guidelines to make the "face" in the money icon a rounded rect:

![screen shot 2016-06-16 at 11 18 21 am](https://cloud.githubusercontent.com/assets/618551/16124325/24a25e7e-33b4-11e6-8c27-f771beb0920c.png)

Instead of an oval:

![screen shot 2016-06-16 at 11 19 18 am](https://cloud.githubusercontent.com/assets/618551/16124342/3400cff4-33b4-11e6-8eeb-392c93e48812.png)

**Comment by folletto** [comment]
Well thought! 👍
