### ISSUE TITLE
Build: check for a NPM native version to build PDFs

### ISSUE THREAD

**Issue by folletto** [Automattic/gridicons#193]
Currently to build PDFs we use `CairoSVG` with these instructions:

```
sudo easy_install pip
sudo pip install cairosvg
brew install cairo
sh makepdfs.sh
```

Which uses Python thus it's currently a separate script.

Would be a good improvement to find an NPG/Grunt native way to automate everything.

**Comment by drw158** [comment]
possible alternatives

https://www.npmjs.com/package/librsvg

https://github.com/walling/node-rsvg

https://github.com/papandreou/node-inkscape

**Comment by drw158** [comment]
I believe we can close this because we use pdfkit now. https://github.com/Automattic/gridicons/blob/87c9fce08b4a9f184b9fb4963228757fdd4f4e74/package.json#L45

**Comment by folletto** [comment]
Correct. :)
