### ISSUE TITLE
Code icon looks like left/light "chevron" arrows

### ISSUE THREAD

**Issue by iseulde** [Automattic/gridicons#197]
The code icon is a bit confusing to me because it could look like two small "chevron" arrows next to each other. To solve the issue, and to make the icon clearer, I would add a slash in he middle: `</>`.

While I was playing with a code block + up and down arrows, I ended up with this:

<img width="78" alt="screenshot 2017-02-15 12 32 00" src="https://cloud.githubusercontent.com/assets/4710635/22972679/018b76e6-f37b-11e6-9466-1ce7dff20ecf.png">

**Comment by drw158** [comment]
Fixed in #221
