### ISSUE TITLE
New icon: half star?

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#199]
Do we need a half star icon for ratings?

![screen shot 2017-02-16 at 10 25 11 am](https://cloud.githubusercontent.com/assets/618551/23030060/3b6b00cc-f432-11e6-83a4-ac9f027ad006.png)

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
@drw158 No. We can do it with CSS or with a single SVG icon rather than multiple. You can just make a half SVG layer to colorize via CSS when needed.
