### ISSUE TITLE
New icon: Cursor

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/gridicons#200]
**What:** Cursor icon like one of the quick comps in the layers of this file: 
[gridicons_cursor.ai.zip](https://github.com/Automattic/gridicons/files/832094/gridicons_cursor.ai.zip)
<img width="45" alt="screen shot 2017-03-09 at 2 37 37 pm" src="https://cloud.githubusercontent.com/assets/22752103/23767257/f8d79446-04d5-11e7-8cd9-24497b394373.png">
<img width="50" alt="screen shot 2017-03-09 at 2 37 42 pm" src="https://cloud.githubusercontent.com/assets/22752103/23767262/fa96c810-04d5-11e7-9d0e-ed23166cc7e9.png">

**Why / Where:** For instances like the "Clicks" view in Calypso stats. No other icon can substitute in and the visual system created the standard that there will be an icon there. _The build for this particular use case will start soon._

_Frankencomp of a use case:_
<img width="684" alt="screen shot 2017-03-09 at 2 13 38 pm" src="https://cloud.githubusercontent.com/assets/22752103/23766506/1ce10ef6-04d3-11e7-963c-1df17ba7b9ac.png">

**Comment by drw158** [comment]
Would a hand work? I think it might be more versatile.

![screen shot 2017-03-16 at 10 46 34 am](https://cloud.githubusercontent.com/assets/618551/24005031/e5bbbbc0-0a35-11e7-9efb-28edef5c61d0.png)
![screen shot 2017-03-16 at 10 47 47 am](https://cloud.githubusercontent.com/assets/618551/24005082/03c4245e-0a36-11e7-9119-30c7bbdccc3c.png)

**Comment by ashleighaxios** [comment]
Sure would! Nice idea

**Comment by drw158** [comment]
I have 2 wip icons so far

![screen shot 2017-03-20 at 11 19 11 am](https://cloud.githubusercontent.com/assets/618551/24109594/1f9ccb8c-0d5f-11e7-8c19-4a11cce99936.png)
![screen shot 2017-03-20 at 11 02 54 am](https://cloud.githubusercontent.com/assets/618551/24109596/213a7f7a-0d5f-11e7-8ab7-26364148aec0.png)

**Comment by ashleighaxios** [comment]
The arrow/cursor is so iconic and scales so well that it has a head start, but I do like the idea of the hand as something more device-agnostic and human.

**Comment by drw158** [comment]
There doesn't seem to be an immediate need for this, but we can always reopen if there is another request for it.
