### ISSUE TITLE
New icon: Plan

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#202]
I think we need a better icon for `plan`. Currently we use the clipboard.

Some ideas:

- Heart
- Heart in a box
- Lightning bolt
- Up arrow
- present
- rocket
- variation of the star

**Comment by folletto** [comment]
Note: we use the lightning bolt to signify "Offline" #187.

**Comment by drw158** [comment]
Closing for now, because we are using the Jetpack icon.
