### ISSUE TITLE
New Icon: Password

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/gridicons#210]
I've worked up an idea, but I'm pretty terrible with Illustrator. I tried my best, but if you can make it better, please do.

<img width="630" alt="screen shot 2017-05-25 at 3 17 58 pm" src="https://cloud.githubusercontent.com/assets/191598/26466624/5d075eba-415d-11e7-9eb4-a4b01cd1bece.png">

<img width="236" alt="screen shot 2017-05-25 at 3 39 36 pm" src="https://cloud.githubusercontent.com/assets/191598/26467395/664192ea-4160-11e7-91ef-d81f76ffd977.png">

It feels a little thin when compared to the rest of the family, but I'm unsure how to resolve that.

Here's the illustrator file: [password.ai.zip](https://github.com/Automattic/gridicons/files/1030035/password.ai.zip)

**Comment by drw158** [comment]
We usually use the lock for 'password', and I believe we currently use the lock for the password field in the native apps. Any reason not to use the lock? Where would this icon be used?

**Comment by shaunandrews** [comment]
We're looking to use this icon to denote a post's privacy status, which also include the lock and lock-open:

<img width="370" alt="screen shot 2017-05-25 at 8 04 27 pm" src="https://cloud.githubusercontent.com/assets/191598/26475354/7a7bee5c-4185-11e7-9da2-72fdeff98099.png">

**Comment by folletto** [comment]
That's a hard one! 

I feel the dots might be too similar to the "•••" ellipsis/overflow Gridicon... otherwise would work nice. What about using a "key" there: lock - lock - key seems a viable metaphor to me?

**Comment by drw158** [comment]
Some screenshots, just for reference:

![screen shot 2017-05-26 at 11 40 08 am](https://cloud.githubusercontent.com/assets/618551/26503895/20172b6a-4208-11e7-872a-fe9c0b4e2367.png)
![screen shot 2017-05-26 at 11 39 05 am](https://cloud.githubusercontent.com/assets/618551/26503897/220bb1e8-4208-11e7-9718-0d02e7ff53ef.png)

- I think we could use our `globe` icon for Public (we have a separate icon for domains now), but the open lock is good too. It would be nice to have it added anyway.
- We could use the `user` icon for "Members Only". That would free up the lock icon to be used for "Password Protected".
- If we don't end up using the lock icon for "Password Protected", I think a shield would be nice. I've been wanting to add one, and I think it emphasizes the important part, "protected".

Overall, I think if we use more unique icons for each item, perhaps it would be easier to grok at a glance.

Quick mockups of what I'd prefer:

![screen shot 2017-05-26 at 11 47 51 am](https://cloud.githubusercontent.com/assets/618551/26504201/32e015c6-4209-11e7-8857-c74b889be2f1.png)

![screen shot 2017-05-26 at 11 51 43 am](https://cloud.githubusercontent.com/assets/618551/26504317/b7eaa9e8-4209-11e7-93c8-e66e5aa407d3.png)

**Comment by michaeldcain** [comment]
I really like the `globe`, `user`, and `lock` combination. I can try it out in the component.

**Comment by drw158** [comment]
I'll close this for now since that PR was merged.
