### ISSUE TITLE
New Icon: Lock Opened

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/gridicons#211]
<img width="835" alt="screen shot 2017-05-25 at 3 50 01 pm" src="https://cloud.githubusercontent.com/assets/191598/26467739/d7e07078-4161-11e7-9a75-9537d7ebdd31.png">

I based this off the existing lock icon.

<img width="260" alt="screen shot 2017-05-25 at 3 49 43 pm" src="https://cloud.githubusercontent.com/assets/191598/26467746/e04579f2-4161-11e7-897c-22babc2f6e79.png">

[lock-open.ai.zip](https://github.com/Automattic/gridicons/files/1030054/lock-open.ai.zip)

**Comment by drw158** [comment]
I think this is good. I can dig into the file later.

**Comment by folletto** [comment]
Nice! 👍

**Comment by drw158** [comment]
In an effort to try to use non-angled lines and 2dp gaps if we can, how about this:

![screen shot 2017-05-26 at 3 20 20 pm](https://cloud.githubusercontent.com/assets/618551/26511285/faa0be0e-4226-11e7-8a62-8aada2edb969.png)

raised the "U" part by 1px and cut off the bottom.

**Comment by drw158** [comment]
There doesn't seem to be an immediate need for this, but we can always reopen if there is another request for it.
