### ISSUE TITLE
Add babel-runtime to dependencies

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/gridicons#212]
I tried to create a new nodejs Electron app with Gridicons by adding the package using npm. When run, I get this error: `Cannot find module 'babel-runtime/core-js/object/get-prototype-of'`. 

It is, indeed, at the very beginning of the compiled Gridicons `build/index.js` file after building:

```
var _getPrototypeOf=require('babel-runtime/core-js/object/get-prototype-of')
```

Installing the `babel-runtime` package from npm solves the issue.

I'm not sure why it's required, but perhaps it should be a dependency or a peer dependency?

**Comment by folletto** [comment]
I'm not sure... I tried looking in the Gridicon source and I can't find a reference to it. Maybe something is injecting it?

**Comment by sirbrillig** [comment]
Yeah, it's definitely not in the source. I imagine it has something to do with the build process, but there's a lot going on in there and I'm a little unclear on how it all works.

**Comment by drw158** [comment]
Thanks for trying it out on a project @sirbrillig 

Invoking @gwwar in case she has a few minutes to take a look.

**Comment by gwwar** [comment]
Oh, odd that is being added to the final file. Instead of adding this as a dep, we should tweak the build so the final file is a valid self contained es5 file.

I might have gotten the options wrong in `Gruntfile.js`
