### ISSUE TITLE
Update example icons on the gallery site

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/gridicons#228]
There has been some recent updates and additions to gridicons but it looks the example library [here](https://wpcalypso.wordpress.com/devdocs/design/gridicons)
 was not updated.

Can we please update the example library.

**Comment by folletto** [comment]
This isn't a Gridicons issue, it's a Calypso issue. 

Gridicons example is here: http://automattic.github.io/gridicons/

If you want to update Calypso documentation open an issue here: https://github.com/Automattic/wp-calypso/issues

**Comment by SergioEstevao** [comment]
@folletto why don't we link to this page on the Readme instead? is this updated automatically?

**Comment by folletto** [comment]
It's a good question. :D 
Ok for you if I reopen it as a request to update the README? :D
