### ISSUE TITLE
New Icon: Play

### ISSUE THREAD

**Issue by SergioEstevao** [Automattic/gridicons#229]
At the moment we have a Pause icon on the library but it looks we don't have the counter part to do play. 

Can we have a Play icon?

My use case scenario is on the mobile apps we have support for videos on the editor. By default they start paused and it will be nice to overlay a Play icon on top to indicate to the users that it's a video and you can play them.

Here is an example of the current icon we have that is code generated:

<img width="344" alt="screen shot 2017-06-20 at 12 36 50" src="https://user-images.githubusercontent.com/651601/27331404-326e843c-55b5-11e7-9b8e-21c730e63896.png">

**Comment by drw158** [comment]
see #233
