### ISSUE TITLE
New icon: Jetpack logo (plans)

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#240]
Unfortunately this is another logo, but we need to add it for the time being.

We use the Jetpack logo for the Plans icon:

![screen shot 2017-07-19 at 2 49 23 pm](https://user-images.githubusercontent.com/618551/28386587-ad4eec26-6c91-11e7-8076-f9adce7c209d.png)

Much like the W logo for 'My Sites', the Jetpack logo should be added to Gridicons and named 'plans' or 'plan'.

We need to be clear that this logo is only to be used for the Plans icon, because the logo vectors will be tweaked a bit because of the small size. There is a separate component in Calypso for the unaltered logo.

This is necessary, because at the moment, the svg being using for the Plans icon does not fit the Gridicons template, and it appears bigger than other circle icons.

**Comment by drw158** [comment]
Svg file: 

[jetpack.zip](https://github.com/Automattic/gridicons/files/1160617/jetpack.zip)

**Comment by sirreal** [comment]
Just adding a note that I believe the zip above contains an outdated icon
