### ISSUE TITLE
Doc: review of page for SVG guidelines

### ISSUE THREAD

**Issue by folletto** [Automattic/gridicons#265]
I've started a page for the source SVG guidelines:
https://github.com/Automattic/gridicons/wiki/Guidelines-for-SVG-Sources

The idea is to have some standardized guidance on how we should have the SVGs in the source folder.

First draft copy-pasted below.

---

### Guidelines for SVG Sources

Here's the current draft for a guideline to write the SVG used in the icon set sources. It's still in progress, and feel free to review.

1. Remove any internal `style` reference (`fill` attributes excepted to make the icon readable, they will get removed in the grunt process).
2. Remove any `xml:space` and `enable-background`.
3. Remove any "generator" comment (keep comments that might be added to clarify the SVG)
4. Remove any superfluous `id` or `class` attribute, or rename the ones that are useful to be referenced specifically.
5. Remove any superfluous nesting.
6. Make sure the cleaned up SVG still renders as the original.

See [this SVG](https://github.com/Automattic/gridicons/blob/b5d36227e554502e78c403c27e6779fc46c470fd/sources/svg/gridicons-create.svg?short_path=34ad600) for reference.

**Comment by folletto** [comment]
@jancavan noted in https://github.com/Automattic/gridicons/pull/264#issuecomment-350864681 that we might not even need fill as the SVG will likely get a default color? 

Needs to be tested I guess :D

**Comment by jancavan** [comment]
Yeah, definitely needs to be tested. I removed the `fill` attribute from the icons in that PR and they seem to be viewable just fine.

**Comment by jasmussen** [comment]
Nice! Great start.

Much of what is achieved in following those, can be achieved by dropping the SVG in https://jakearchibald.github.io/svgomg/ — right?

**Comment by jancavan** [comment]
@jasmussen I think so, depending on the settings/features you select. I had to manually just clean up mine though!

**Comment by folletto** [comment]
Thanks for the link, I'll review the tool above!

**Comment by folletto** [comment]
> Yeah, definitely needs to be tested. I removed the fill attribute from the icons in that PR and they seem to be viewable just fine.

I cross checked this, and confirmed. Well spotted ⭐️ 

I also checked the [1.1](https://www.w3.org/TR/SVG/painting.html#FillProperties) and [2.0 spec](https://www.w3.org/TR/SVG2/painting.html#SpecifyingFillPaint) to be sure, and yes, `fill` has a default value that is not `transparent` but `black`. TIL.

**Comment by folletto** [comment]
> Much of what is achieved in following those, can be achieved by dropping the SVG in https://jakearchibald.github.io/svgomg/ — right?

I tested this. It does a lot indeed!

I'd note the following:

1. It strips IDs too (all or nothing). Not all IDs imho should be stripped. The actual icon one could stay. Even if... we have a build process after that? 
2. It should be put in "Prettify" mode, as otherwise it goes for max compression. I'd appreciate if the source file stays readable as its source might contain useful bits for CSS animations.
3. It seems to recalculate the curves too. This means that it's important to cross-check if that tool is used on the actual output to see if it still matches correctly. This shouldn't be an issue, but as any manipulation on vertexes I think it should be cross-checked.
4. I'd probably keep the `xml` declaration, but... maybe not? I'm not sure why yes or why no.

**Comment by folletto** [comment]
Ok, updated. Check if it looks alright:

---

Here's the current draft for a guideline to write the SVG used in the icon set sources. It's still in progress, and feel free to review.

1. Remove any internal `style` reference, `fill` included (it defaults to black).
2. The `svg` tag should contain only the `xmlns` and `viewBox` attributes.
3. Keep or add the `<?xml version="1.0" encoding="UTF-8"?>` declaration.
4. Remove any "generator" or superfluous comment. Keep comments that clarify the SVG content.
5. Remove any superfluous `id` or `class` attribute, keep the ones that are semantically meaningful.
6. Remove any superfluous empty tag and fix any weird nesting.
7. Make sure the cleaned up SVG still renders as the original.


### Tools

If you use [SVGOMG](https://jakearchibald.github.io/svgomg/), which is really good, make sure you configure it to do "Prettify" (the file should stay readable) and to re-introduce the meaningful bits from the list above.
