### ISSUE TITLE
How can I use this in WordPress instead of dashicons?

### ISSUE THREAD

**Issue by shivapoudel** [Automattic/gridicons#278]
I want to use gridicon in WordPress CPT and `add_menu_page` but fill is not set so all icons are black.

![capture1](https://user-images.githubusercontent.com/3774827/35477271-9b5c7b8a-03e7-11e8-9a16-abd59228b657.PNG)

**Comment by drw158** [comment]
Hey there, according to this, replacing `fill="none"` with `fill="black"` should work.

https://stackoverflow.com/questions/30620226/custom-svg-admin-menu-icon-in-wordpress/42265057#42265057

Can you test that out and see if it works?

**Comment by shivapoudel** [comment]
@drw158 Agreed. With the fill attribute it works great but when on admin load it flickers with colors to match every time.

**Comment by drw158** [comment]
My guess is that there is some sort of override in the WP Admin CSS.
