### ISSUE TITLE
Add icons: Fullscreen/exit fullscreen

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#40]
Ideas:

![screen shot 2015-06-01 at 9 51 04 am](https://cloud.githubusercontent.com/assets/618551/7915533/c28ff0a8-0843-11e5-9846-d1a93cdab64d.png)

**Comment by melchoyce** [comment]
Have a need for this now! We need a "full screen" icon for the Customizer:

<img width="660" alt="screen shot 2016-03-22 at 1 19 32 pm" src="https://cloud.githubusercontent.com/assets/2846578/13961263/3ac58a3e-f032-11e5-94ae-c48ba1e43c47.png">

This would replace "( < ) Collapse"

**Comment by folletto** [comment]
+1

I think that works. :)

**Comment by drw158** [comment]
I think the one @melchoyce made works well. Do we need an exit fullscreen icon?

**Comment by melchoyce** [comment]
Yeah, an opposite one would be good. What do you think of this? 

<img width="94" alt="screen shot 2016-03-22 at 3 14 44 pm" src="https://cloud.githubusercontent.com/assets/2846578/13964605/df56ba1a-f040-11e5-9187-0fda6f8bd10b.png">
