### ISSUE TITLE
Add icon: Price

### ISSUE THREAD

**Issue by drw158** [Automattic/gridicons#47]
Previously mentioned here: #35

**Comment by drw158** [comment]
The work I've done on price so far (ignore the stray dots)

![screen shot 2016-05-26 at 9 49 52 am](https://cloud.githubusercontent.com/assets/618551/15578733/4598d33a-2327-11e6-984e-16a7a669c8f9.png)

**Comment by folletto** [comment]
This seems a good direction:

![screen shot 2016-05-26 at 15 52 56](https://cloud.githubusercontent.com/assets/4389/15578828/f1881d72-2359-11e6-9d17-d1201f5bcbbd.png)

Would be worth adding a slight contour to the dot to make a face silhouette? :D

**Comment by drw158** [comment]
![screen shot 2016-05-27 at 3 08 17 pm](https://cloud.githubusercontent.com/assets/618551/15619928/dd569ba8-241c-11e6-8c4b-79cb759bbc1e.png)
![screen shot 2016-05-27 at 3 08 08 pm](https://cloud.githubusercontent.com/assets/618551/15619930/df67e8b6-241c-11e6-8c03-ca14d5a78b73.png)
