### ISSUE TITLE
Add Icon: (Theme) Features

### ISSUE THREAD

**Issue by folletto** [Automattic/gridicons#53]
We need an icon for general theme features. 

Current screenshot from the Theme Showcase 4.0:

![screen shot 2015-07-17 at 18 30 39](https://cloud.githubusercontent.com/assets/4389/8753244/fc7eb906-2cb1-11e5-8812-949d26a17554.png)

**Comment by drw158** [comment]
@folletto Looks like Feature is using the customize icon, which I think works pretty well, maybe even better than the concepts presented here. Could we close this issue?

**Comment by folletto** [comment]
I'd prefer to use something more specific, but I agree that for the time being it works.

**Comment by drw158** [comment]
Ok, we can reopen if needed.
