### ISSUE TITLE
New Posts Icon

### ISSUE THREAD

**Issue by isaackeyet** [Automattic/gridicons#84]
I've been thinking about the post/posts icon for [some time](https://github.com/Automattic/gridicons/issues/9#issuecomment-64089835).
# The Past

<img width="249" alt="screen shot 2015-08-27 at 22 19 34" src="https://cloud.githubusercontent.com/assets/3073557/9532153/17f9c6d0-4d0a-11e5-884d-47eceb2e0a53.png">

I think the old thumbtack fails/succeeds because:
- Now widely recognized by most of the WP world.
- Skeumorphism-dependent (you have to know what it is).
- Weird weight (takes careful balancing visually).
- Is confusing considering you can sometimes "pin" things depending on what you use WP for.
- Signals pinning board, doesn't signify relevancy.
# The Now

<img width="287" alt="screen shot 2015-08-27 at 22 20 08" src="https://cloud.githubusercontent.com/assets/3073557/9532193/5f0afecc-4d0a-11e5-9229-d279f89b072a.png">

I think the current icon fails/succeeds because:
- More relevant for most than a thumbtack.
- Only signifies text (not photos/videos/post formats).
- Is visually weighted less than pages and many other icons (it stands out).
- Only signifies one piece of content.
- Not friendly for RTL/symbol languages? ;)
- Doesn't signify relevancy.
# The Future

<img width="285" alt="screen shot 2015-08-27 at 22 24 53" src="https://cloud.githubusercontent.com/assets/3073557/9532208/7b5cb7b4-4d0a-11e5-92ee-241f0da4f164.png">

After [some exploration](https://cloudup.com/cXpeTntyyd6), I've arrived at my proposed new icon. I think it works because it:
- Signifies multiple things in a generic shape: a bullet in a list, a camera, a block of content, a pussle piece, a location, a looking glass, a stackable toy, and most importantly a _notification_ (more on this below).
- Is actually really close to the CPT icon, using the same general shape and a dot to signify one CPT!
- Is better weighted compared to other icons, most importantly including the Pages icon and writing icons (see below).
- Ties in with the Create icon's shape, but a filled block means the post can already be there (hence it works for lists). In comparison, the Create icon is outlined, meaning it's not yet "active". Once published/saved it will be a filled box and available in a posts list.
- The dot signifies an item in a stack in the same way that the dot on the Notification bell icon doesn't mean that there's only 1 item to be seen: it can be more than one, but it means that there's content to be seen. The positioning of the dot is different as it's not a secondary indicator for another icon (compare to \* icon or the dot for Notifications). Instead, it builds a mental picture of creating content to generate notifications for yourself and others. Each post, if you have subscriber, would invoke that same dot for them. Each post may have interesting stats to look at.
- Creates such a generic shape that it could be universally adopted over time to signify a "post", "status update", "news bulletin", etc. Compare to the Location icon and how universal the drop marker is nowadays.

Given that we don't have the same icon as Core anymore and the current one falls short in many ways I don't think it'd be a big deal to change the icon for posts.

Some examples..
<img width="283" alt="screen shot 2015-08-27 at 22 10 10" src="https://cloud.githubusercontent.com/assets/3073557/9532403/cad16abe-4d0b-11e5-810d-e1a8f437cdd3.png">
<img width="627" alt="screen shot 2015-08-27 at 22 09 24" src="https://cloud.githubusercontent.com/assets/3073557/9532404/cad6119a-4d0b-11e5-85b7-44c7d0b15bec.png">
<img width="657" alt="screen shot 2015-08-27 at 22 09 12" src="https://cloud.githubusercontent.com/assets/3073557/9532405/cad710ae-4d0b-11e5-84f6-089424c7ab44.png">
<img width="611" alt="screen shot 2015-08-27 at 22 08 38" src="https://cloud.githubusercontent.com/assets/3073557/9532406/caeddf78-4d0b-11e5-99ef-d11f99341f6c.png">
<img width="434" alt="screen shot 2015-08-27 at 22 36 55" src="https://cloud.githubusercontent.com/assets/3073557/9532478/2eb0d2cc-4d0c-11e5-9b8a-de59751a027b.png">

Thoughts?

**Comment by drw158** [comment]
Archiving this issue for now. This is a very good concept, but I think the proposed icon is a bit too abstract. The current posts icon is not perfect, but I think it's recognizable. I'd love more ideas for the Posts icon though.
