### ISSUE TITLE
New icon: Sitemap or Network

### ISSUE THREAD

**Issue by rickybanister** [Automattic/gridicons#99]
The noticon looks like this:

![screen shot 2015-09-25 at 5 23 08 pm](https://cloud.githubusercontent.com/assets/437258/10112547/1cfc713a-63aa-11e5-858e-dd65cd89216f.png)

This is used to signify a multi-user install (and might have other uses)

**Comment by drw158** [comment]
This one's pretty old, and we haven't needed it, so closing for now.
